// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eacxofmootibbslmuojd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhY3hvZm1vb3RpYmJzbG11b2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNjE4NTcsImV4cCI6MjA0OTgzNzg1N30.PNij_JUpubrsUiNzoL5uCUmgLyIJwWaImraO--Fbvu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);